class AuthErrorCodes:
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    MISSING_ACCESS_TOKEN = "MISSING_ACCESS_TOKEN"
    INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN"
    MISSING_REFRESH_TOKEN = "MISSING_REFRESH_TOKEN"
    INVALID_SESSION = "INVALID_SESSION"
    EMAIL_NOT_ALLOWED = "EMAIL_NOT_ALLOWED"
    INVALID_SIGNUP_SECRET = "INVALID_SIGNUP_SECRET"
    USER_NOT_FOUND = "USER_NOT_FOUND"
