class ExternalErrorCodes:
    INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    EXCHANGE_RATE_PROVIDER_UNAVAILABLE = "EXCHANGE_RATE_PROVIDER_UNAVAILABLE"
    EXCHANGE_RATE_PROVIDER_INVALID_RESPONSE = (
        "EXCHANGE_RATE_PROVIDER_INVALID_RESPONSE"
    )
