class OdinErrorCodes:
    INCOME_SOURCE_NOT_FOUND = "INCOME_SOURCE_NOT_FOUND"
    ALLOCATION_BOX_NOT_FOUND = "ALLOCATION_BOX_NOT_FOUND"
    SUBCATEGORY_NOT_FOUND = "SUBCATEGORY_NOT_FOUND"
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
    PERCENTAGE_EXCEEDS_LIMIT = "PERCENTAGE_EXCEEDS_LIMIT"
    ONBOARDING_PREREQUISITES_NOT_MET = "ONBOARDING_PREREQUISITES_NOT_MET"
